### PR TITLE
Cenj 33 addition policy details view containing wireframe

### PR DESCRIPTION
**Pull request by SolerJapan**
Added Policy Details view

### CODE REVIEW

**Review by Marcus-Johnson — APPROVED** [review]
--Comment left for future use, code is professional!

**Comment by Marcus-Johnson** [comment]
Waiting for @AbelRodriguezGuillen to finish his UI review

**Review by AbelRodriguezGuillen — COMMENTED** [review]
Everything looks good on my end

**Review by AbelRodriguezGuillen — APPROVED** [review]
Everything looks good on my end

**Pull request merged**
